"use client";

import { useCallback, useEffect, useState } from "react";

type BeforeInstallPromptEvent = Event & {
  readonly platforms: ReadonlyArray<string>;
  readonly userChoice: Promise<{ outcome: "accepted" | "dismissed"; platform: string }>;
  prompt: () => Promise<void>;
};

export function PwaRegister() {
  const [installEvent, setInstallEvent] = useState<BeforeInstallPromptEvent | null>(null);
  const [dismissed, setDismissed] = useState(false);

  // Register the service worker generated by next-pwa.
  useEffect(() => {
    if (typeof window === "undefined") return;
    if (process.env.NODE_ENV === "development") return;
    if (!("serviceWorker" in navigator)) return;

    const onLoad = () => {
      navigator.serviceWorker.register("/sw.js").catch(() => {
        // Silent: SW registration is best-effort.
      });
    };

    if (document.readyState === "complete") {
      onLoad();
    } else {
      window.addEventListener("load", onLoad, { once: true });
      return () => window.removeEventListener("load", onLoad);
    }
  }, []);

  // Capture the install prompt so we can trigger it from a friendly button.
  useEffect(() => {
    if (typeof window === "undefined") return;

    const onBeforeInstall = (event: Event) => {
      event.preventDefault();
      setInstallEvent(event as BeforeInstallPromptEvent);
    };

    const onInstalled = () => {
      setInstallEvent(null);
    };

    window.addEventListener("beforeinstallprompt", onBeforeInstall);
    window.addEventListener("appinstalled", onInstalled);

    return () => {
      window.removeEventListener("beforeinstallprompt", onBeforeInstall);
      window.removeEventListener("appinstalled", onInstalled);
    };
  }, []);

  const handleInstall = useCallback(async () => {
    if (!installEvent) return;
    try {
      await installEvent.prompt();
      await installEvent.userChoice;
    } finally {
      setInstallEvent(null);
    }
  }, [installEvent]);

  if (!installEvent || dismissed) return null;

  return (
    <div
      role="region"
      aria-label="Instalar Pianitos"
      className="fixed bottom-4 right-4 z-50 flex w-[min(280px,calc(100vw-2rem))] items-center gap-2 rounded-full border border-brand-300 bg-white px-3 py-2 shadow-lg"
    >
      <button
        type="button"
        onClick={handleInstall}
        className="kid-button-secondary flex-1 truncate rounded-full px-3 py-1 text-sm"
      >
        Instalar Pianitos
      </button>
      <button
        type="button"
        onClick={() => setDismissed(true)}
        aria-label="Cerrar sugerencia de instalación"
        className="grid h-8 w-8 place-items-center rounded-full text-brand-700 hover:bg-brand-50"
      >
        <span aria-hidden="true">×</span>
      </button>
    </div>
  );
}

export default PwaRegister;
